#!/usr/bin/env python3
"""Regenerate the track status board from story frontmatter.

Deterministic and dependency-free (Python 3 standard library only). Scans
`<docs>/stories/*.md`, reads each story's YAML-ish frontmatter, and rewrites the
generated region of `<docs>/stories/README.md` (between the BEGIN/END markers).
Everything outside the markers is preserved.

Usage:
    python3 gen_board.py [docs-dir]      # docs-dir defaults to "docs"

Exit codes:
    0  board rewritten (or already current)
    1  hard error (missing board, missing markers, no stories dir)

The algorithm is mirrored in prose in BOARD_SPEC.md so an agent can reproduce the
exact same output by hand when python3 is unavailable.
"""

import os
import re
import sys

BEGIN = "<!-- BEGIN track:board -->"
END = "<!-- END track:board -->"
GENERATED_NOTE = (
    "<!-- Generated by /track:board (track plugin) from story frontmatter. "
    "Do not hand-edit this region; edit the stories and re-run /track:board. -->"
)
KNOWN_STATUSES = ("backlog", "ready", "in-progress", "blocked", "done")
SKIP_FILES = ("README.md", "_TEMPLATE.md")


def parse_frontmatter(text):
    """Return a dict of the leading `---`-fenced frontmatter, or {} if absent."""
    if not text.startswith("---"):
        return {}
    lines = text.splitlines()
    if lines[0].strip() != "---":
        return {}
    data = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if (len(value) >= 2) and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        if key:
            data[key] = value
    return data


def normalize_status(value):
    """Forgiving status: lowercase, collapse whitespace/underscores to hyphens.

    So `In Progress`, `in progress`, and `in_progress` all map to `in-progress`,
    preventing a near-miss from silently dropping a story off the board.
    """
    return re.sub(r"[\s_]+", "-", (value or "").strip().lower())


def parse_priority(value):
    """Extract the first integer from a priority value (`P1`, `1`, `rank 3` -> 1/1/3).

    Returns None if there's no integer.
    """
    m = re.search(r"-?\d+", value or "")
    return int(m.group()) if m else None


def natural_id_key(story_id):
    """Sort key so D-2 precedes D-10 and prefixes group together."""
    m = re.match(r"^([A-Za-z]+)[-_ ]?(\d+)", story_id or "")
    if m:
        return (m.group(1).upper(), int(m.group(2)), story_id)
    return ("~", 0, story_id or "")


def _design_lines(docs_dir, slug):
    path = os.path.join(docs_dir, "designs", slug + ".md")
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as fh:
            return fh.read().splitlines()
    return None


def epic_title(docs_dir, slug):
    """Resolve an epic's display title from its design doc H1, else title-case the slug."""
    lines = _design_lines(docs_dir, slug)
    if lines:
        for line in lines:
            line = line.strip()
            if line.startswith("# "):
                title = re.sub(r"^design\s*[:—-]\s*", "", line[2:].strip(), flags=re.I)
                return title.strip()
    return slug.replace("-", " ").replace("_", " ").title()


def epic_blurb(docs_dir, slug, limit=200):
    """One-line epic summary: the first non-empty line under the design doc's `## Why`.

    Returns "" if there's no design doc or no Why section. Truncated to `limit`
    chars on a word boundary so the board stays scannable.
    """
    lines = _design_lines(docs_dir, slug)
    if not lines:
        return ""
    in_why = False
    for line in lines:
        if re.match(r"^##\s+why\b", line.strip(), flags=re.I):
            in_why = True
            continue
        if in_why:
            if line.strip().startswith("#"):
                break
            if line.strip():
                blurb = line.strip()
                if len(blurb) > limit:
                    blurb = blurb[:limit].rsplit(" ", 1)[0] + "…"
                return blurb
    return ""


def row(story):
    parts = ["- [{id} — {title}]({file})".format(**story)]
    if story.get("pillar"):
        parts.append(story["pillar"])
    if story.get("note"):
        parts.append(story["note"])
    return " · ".join(parts)


def render_grouped(stories, docs_dir):
    """Render rows for Next/Backlog: ungrouped first, then epic groups by slug."""
    ungrouped = [s for s in stories if not s.get("epic")]
    grouped = {}
    for s in stories:
        if s.get("epic"):
            grouped.setdefault(s["epic"], []).append(s)
    out = []
    if ungrouped:
        out.extend(row(s) for s in ungrouped)
    for slug in sorted(grouped):
        out.append("")
        out.append("### {}".format(epic_title(docs_dir, slug)))
        blurb = epic_blurb(docs_dir, slug)
        if blurb:
            out.append("_{}_".format(blurb))
        out.extend(row(s) for s in grouped[slug])
    return out


def section(heading, lines):
    body = "\n".join(lines) if lines else "_None._"
    return "## {}\n{}".format(heading, body)


def build_block(stories, docs_dir):
    by_status = {s: [] for s in KNOWN_STATUSES}
    for s in stories:
        by_status.get(s["status"], []).append(s)

    now = sorted(by_status["in-progress"], key=lambda s: natural_id_key(s["id"]))
    nxt = sorted(
        by_status["ready"],
        key=lambda s: (s.get("priority_sort", float("inf")), natural_id_key(s["id"])),
    )
    blocked = sorted(by_status["blocked"], key=lambda s: natural_id_key(s["id"]))
    backlog = sorted(by_status["backlog"], key=lambda s: natural_id_key(s["id"]))
    done = sorted(by_status["done"], key=lambda s: natural_id_key(s["id"]))

    done_body = "\n".join(row(s) for s in done) if done else "_None yet._"
    done_section = "## Done\n{}".format(done_body)
    if done:
        done_section += "\n\n_See [CHANGELOG.md](../../CHANGELOG.md) for the full released history._"

    parts = [
        GENERATED_NOTE,
        "",
        section("Now (in progress)", [row(s) for s in now]),
        "",
        section("Next (ready — take the top one unless the user named a story)",
                render_grouped(nxt, docs_dir)),
        "",
        section("Blocked", [row(s) for s in blocked]),
        "",
        section("Backlog", render_grouped(backlog, docs_dir)),
        "",
        done_section,
    ]
    return "\n".join(parts)


def main(argv):
    docs_dir = argv[1] if len(argv) > 1 else "docs"
    stories_dir = os.path.join(docs_dir, "stories")
    board = os.path.join(stories_dir, "README.md")

    if not os.path.isdir(stories_dir):
        sys.stderr.write("error: no stories directory at {}\n".format(stories_dir))
        return 1
    if not os.path.isfile(board):
        sys.stderr.write(
            "error: no board at {} (run /track:init to scaffold it)\n".format(board))
        return 1

    warnings = []
    stories = []
    seen_ids = {}

    for name in sorted(os.listdir(stories_dir)):
        if name in SKIP_FILES or not name.endswith(".md"):
            continue
        path = os.path.join(stories_dir, name)
        with open(path, encoding="utf-8") as fh:
            fm = parse_frontmatter(fh.read())
        if not fm:
            warnings.append("{}: no frontmatter — skipped".format(name))
            continue
        sid, title, raw_status = fm.get("id"), fm.get("title"), fm.get("status")
        if not (sid and title and raw_status):
            warnings.append("{}: missing id/title/status — skipped".format(name))
            continue
        status = normalize_status(raw_status)
        if status not in KNOWN_STATUSES:
            warnings.append("{}: unknown status '{}' — skipped".format(name, raw_status))
            continue
        if sid in seen_ids:
            warnings.append("duplicate id '{}' in {} and {}".format(sid, seen_ids[sid], name))
        seen_ids[sid] = name

        story = {"id": sid, "title": title, "status": status, "file": name,
                 "pillar": fm.get("pillar"), "epic": fm.get("epic"),
                 "note": fm.get("note")}
        prio = fm.get("priority")
        if prio not in (None, ""):
            parsed = parse_priority(prio)
            if parsed is not None:
                story["priority_sort"] = parsed
            else:
                warnings.append("{}: priority '{}' has no integer rank".format(name, prio))
        elif status == "ready":
            warnings.append("{}: status 'ready' but no priority".format(name))
        stories.append(story)

    block = build_block(stories, docs_dir)

    text = open(board, encoding="utf-8").read()
    if BEGIN not in text or END not in text:
        sys.stderr.write(
            "error: board {} is missing the {} / {} markers\n".format(board, BEGIN, END))
        return 1
    i = text.index(BEGIN) + len(BEGIN)
    j = text.index(END)
    new_text = text[:i] + "\n" + block + "\n" + text[j:]

    changed = new_text != text
    if changed:
        with open(board, "w", encoding="utf-8") as fh:
            fh.write(new_text)

    done_count = sum(1 for s in stories if s["status"] == "done")
    active = len(stories) - done_count
    print("board {}: {} active story(ies), {} done{}".format(
        "rewritten" if changed else "already current",
        active, done_count, "" if not warnings else " — {} warning(s)".format(len(warnings))))
    for w in warnings:
        print("  warning: {}".format(w))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
